# -*- coding: utf-8 -*-
"""text_to_speech_to_text_automation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-pgDlX7Ou66dmZF69F1_UD8bfmxpCeg
"""

from gtts import gTTS
import os

# Text to convert to speech
text = "abrir o youtube"

# Create a gTTS object
tts = gTTS(text=text, lang='pt')

# Save the audio file
tts.save("audio_youtube.mp4")

# To play the audio file (this might require additional setup depending on your environment)
# os.system("start output.mp4") # For Windows
# os.system("afplay output.mp4") # For macOS
os.system("mpg321 output.mp4") # For Linux (install mpg321 first: sudo apt-get install mpg321)


print("Audio saved as output.mp4")

import speech_recognition as sr
import os
from pydub import AudioSegment

# Initialize the recognizer
r = sr.Recognizer()

# Load the audio file
audio_file_mp4 = "/content/audio_youtube.mp4"
audio_file_wav = "/content/output.wav"

# Convert mp4 to wav using ffmpeg shell command
try:
    os.system(f"ffmpeg -i {audio_file_mp4} {audio_file_wav}")
except Exception as e:
    print(f"Error converting audio file: {e}")

# Load the wav audio file
with sr.AudioFile(audio_file_wav) as source:
    # Adjust for ambient noise
    r.adjust_for_ambient_noise(source)
    # Read the entire audio file
    audio = r.record(source)

try:
    # Recognize speech using Google Web Speech API
    text = r.recognize_google(audio, language='pt-BR')
    print("Converted text:", text)
except sr.UnknownValueError:
    print("Speech Recognition could not understand audio")
except sr.RequestError as e:
    print(f"Could not request results from Google Speech Recognition service; {e}")

import pyautogui as pag

if text == "youtube" or "YOUTUBE":
  pag.press("win")
  pag.write("youtube")
  pag.press("enter")

elif text == "firefox" or "FIREFOX":
  pag.press("win")
  pag.write("firefox")

elif text == "google" or "GOOGLE":
  pag.press("win")
  pag.write("google")

elif text == "whatsapp" or "WHATSAPP":
  pag.hotkey("ctrl", "shift", "w")