# -*- coding: utf-8 -*-
"""classification_recomendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-U-WaVmf5d8Loe7lA434v4JXexA9NvM
"""

from sklearn.datasets import fetch_openml

fashion = fetch_openml('fashion-mnist',version=1)

fashion.keys

X,y =fashion['data'],fashion['target']

X.shape

X_train,X_test,y_train,y_test = X[:20000],X[60000:],y[:20000],y[60000:]

from sklearn.linear_model import SGDClassifier
model = SGDClassifier(random_state=42)

model.fit(X_train,y_train)

model.predict(X[:100])

import cv2
import numpy as np

# carrega a imagen
image_path = '/content/105186615.jpg'
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

# Redefine a imagem para 28x28 pixels
img_resized = cv2.resize(img, (28, 28), interpolation=cv2.INTER_AREA)

# transforma para um array 1D
img_flattened = img_resized.flatten()

# Redefine a imagem para um array 2D
img_input = img_resized.reshape(1, -1)

img_label = model.predict(img_input)[0]

print(f"O rotulo para esta imagen e: {img_label[0]}")

import matplotlib.pyplot as plt
import numpy as np

# Get the predicted label from the previous cell
label = img_label

# Find indices of images with the predicted label
indices_label = y[y == label].index

# Select up to 10 random indices from the found indices
num_imagems = min(len(indices_label), 10)
random_indices = np.random.choice(indices_label, size=num_imagems, replace=False)

# Display the imagens
plt.figure(figsize=(12, 6))
for i, index in enumerate(random_indices):
    image_data = X.iloc[index].values.reshape(28, 28)
    true_label = y.iloc[index]

    plt.subplot(2, 5, i + 1)
    plt.imshow(image_data, cmap='binary')
    plt.title(f"Label: {true_label}")
    plt.axis('off')

plt.tight_layout()
plt.show()

